#!/usr/bin/env python3
"""Generate application template catalog YAML files from in-script definitions."""

from __future__ import annotations

from collections import defaultdict
from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR.parent
OUTPUT_DIR = BACKEND_DIR / "catalog" / "templates"

OPTIMIZED_FORWARD_HEADERS = [
    {"name": "X-Forwarded-Proto", "value": "https"},
    {"name": "Host", "value": "$host"},
]


def tpl(slug: str, name: str, group: str, category: str, **kwargs: Any) -> dict[str, Any]:
    """Build an application template dict with sensible defaults."""
    optimized = kwargs.pop("optimized", False)
    large_upload = kwargs.pop("large_upload_support", False)
    websocket = kwargs.pop("websocket_support", False)
    protocol = kwargs.pop("default_upstream_protocol", "http")
    port = kwargs.pop("default_upstream_port", 8080)
    availability = kwargs.pop("availability_level", "free")
    tags = kwargs.pop("tags", [])
    documentation_url = kwargs.pop("documentation_url", None)
    security_notes = kwargs.pop("security_notes", None)

    template: dict[str, Any] = {
        "slug": slug,
        "name": name,
        "description": kwargs.pop("description", f"Reverse proxy template for {name}."),
        "group": group,
        "category": category,
        "icon": kwargs.pop("icon", "app"),
        "tags": tags,
        "availability_level": availability,
        "optimized": optimized,
        "default_upstream_protocol": protocol,
        "default_upstream_port": port,
        "websocket_support": websocket,
        "large_upload_support": large_upload,
        "recommended_client_max_body_size": kwargs.pop("recommended_client_max_body_size", None),
        "recommended_proxy_read_timeout": kwargs.pop("recommended_proxy_read_timeout", None),
        "recommended_proxy_send_timeout": kwargs.pop("recommended_proxy_send_timeout", None),
        "recommended_proxy_connect_timeout": kwargs.pop("recommended_proxy_connect_timeout", None),
        "https_upstream_supported": kwargs.pop(
            "https_upstream_supported", protocol == "https"
        ),
        "http_to_https_redirect_default": kwargs.pop("http_to_https_redirect_default", True),
        "recommended_headers": kwargs.pop("recommended_headers", []),
        "security_headers": kwargs.pop("security_headers", []),
        "health_check_path": kwargs.pop("health_check_path", None),
        "rate_limit_recommendation": kwargs.pop("rate_limit_recommendation", None),
        "notes": kwargs.pop("notes", None),
        "security_notes": security_notes,
        "documentation_url": documentation_url,
        "long_description": kwargs.pop("long_description", None),
        "slug_aliases": kwargs.pop("slug_aliases", []),
        "hsts_recommended": kwargs.pop("hsts_recommended", False),
    }

    if large_upload and not template["recommended_client_max_body_size"]:
        template["recommended_client_max_body_size"] = "1G"

    if optimized:
        template["recommended_proxy_read_timeout"] = (
            template["recommended_proxy_read_timeout"] or "3600s"
        )
        template["recommended_proxy_send_timeout"] = (
            template["recommended_proxy_send_timeout"] or "3600s"
        )
        template["hsts_recommended"] = True
        if not template["recommended_headers"]:
            template["recommended_headers"] = deepcopy(OPTIMIZED_FORWARD_HEADERS)
        if not template["security_notes"]:
            template["security_notes"] = (
                f"Use extended proxy timeouts and forwarded headers for {name}. "
                "Restrict admin access to trusted networks."
            )

    template.update(kwargs)
    return template


INFRA = "infrastructure-virtualization"
MONITORING = "monitoring-observability"
IDENTITY = "identity-authentication"
HOSTING = "web-hosting-control-panels"
COLLAB = "collaboration-communication"
DEVOPS = "source-control-devops"
STORAGE = "storage-backup"
PRODUCTIVITY = "self-hosted-productivity"
MEDIA = "media-entertainment"
SMART_HOME = "smart-home-iot"
AI = "ai-llm-platforms"
SECURITY = "security"
BUSINESS = "business-applications"
DATABASES = "databases"
NETWORKING = "networking"
DEVELOPER = "developer-tools"
GENERAL = "general"

TEMPLATES: list[dict[str, Any]] = [
    # infrastructure-virtualization
    tpl(
        "proxmox-ve",
        "Proxmox VE",
        INFRA,
        "hypervisor",
        availability_level="enterprise",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=8006,
        websocket_support=True,
        slug_aliases=["proxmox"],
        documentation_url="https://pve.proxmox.com/pve-docs/",
        security_notes="Terminate TLS at the reverse proxy and proxy to HTTPS upstream on port 8006.",
    ),
    tpl(
        "vmware-vcenter",
        "VMware vCenter",
        INFRA,
        "hypervisor",
        availability_level="enterprise",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=443,
        websocket_support=True,
        documentation_url="https://docs.vmware.com/en/VMware-vSphere/index.html",
    ),
    tpl(
        "vmware-esxi",
        "VMware ESXi",
        INFRA,
        "hypervisor",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=443,
        documentation_url="https://docs.vmware.com/en/VMware-vSphere/index.html",
    ),
    tpl(
        "xcp-ng",
        "XCP-ng",
        INFRA,
        "hypervisor",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=443,
        documentation_url="https://xcp-ng.org/docs/",
    ),
    tpl(
        "hyper-v-admin-center",
        "Hyper-V Admin Center",
        INFRA,
        "hypervisor",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=6516,
        websocket_support=True,
        documentation_url="https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/",
    ),
    tpl(
        "portainer",
        "Portainer",
        INFRA,
        "container-platform",
        optimized=True,
        default_upstream_port=9000,
        websocket_support=True,
        documentation_url="https://docs.portainer.io/",
    ),
    tpl(
        "rancher",
        "Rancher",
        INFRA,
        "container-platform",
        availability_level="enterprise",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=443,
        websocket_support=True,
        documentation_url="https://ranchermanager.docs.rancher.com/",
    ),
    tpl(
        "docker-registry",
        "Docker Registry",
        INFRA,
        "registry",
        default_upstream_port=5000,
        large_upload_support=True,
        documentation_url="https://distribution.github.io/distribution/",
    ),
    tpl(
        "harbor",
        "Harbor",
        INFRA,
        "registry",
        availability_level="enterprise",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=443,
        tags=["devops"],
        large_upload_support=True,
        documentation_url="https://goharbor.io/docs/",
    ),
    tpl(
        "kubernetes-dashboard",
        "Kubernetes Dashboard",
        INFRA,
        "orchestration",
        default_upstream_protocol="https",
        default_upstream_port=8443,
        websocket_support=True,
        documentation_url="https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/",
    ),
    tpl(
        "argocd",
        "ArgoCD",
        INFRA,
        "orchestration",
        availability_level="enterprise",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=443,
        websocket_support=True,
        tags=["devops"],
        documentation_url="https://argo-cd.readthedocs.io/",
    ),
    # monitoring-observability
    tpl(
        "grafana",
        "Grafana",
        MONITORING,
        "metrics",
        default_upstream_port=3000,
        websocket_support=True,
        documentation_url="https://grafana.com/docs/grafana/latest/",
    ),
    tpl(
        "prometheus",
        "Prometheus",
        MONITORING,
        "metrics",
        default_upstream_port=9090,
        documentation_url="https://prometheus.io/docs/",
    ),
    tpl(
        "zabbix",
        "Zabbix",
        MONITORING,
        "metrics",
        availability_level="pro",
        default_upstream_port=8080,
        documentation_url="https://www.zabbix.com/documentation/current/en/manual",
    ),
    tpl(
        "uptime-kuma",
        "Uptime Kuma",
        MONITORING,
        "uptime",
        default_upstream_port=3001,
        websocket_support=True,
        documentation_url="https://github.com/louislam/uptime-kuma/wiki",
    ),
    tpl(
        "netdata",
        "Netdata",
        MONITORING,
        "metrics",
        default_upstream_port=19999,
        websocket_support=True,
        documentation_url="https://learn.netdata.cloud/docs/",
    ),
    tpl(
        "kibana",
        "Kibana",
        MONITORING,
        "logging",
        availability_level="enterprise",
        default_upstream_port=5601,
        websocket_support=True,
        documentation_url="https://www.elastic.co/guide/en/kibana/current/index.html",
    ),
    tpl(
        "opensearch-dashboards",
        "OpenSearch Dashboards",
        MONITORING,
        "logging",
        availability_level="enterprise",
        default_upstream_port=5601,
        websocket_support=True,
        documentation_url="https://opensearch.org/docs/latest/dashboards/",
    ),
    tpl(
        "graylog",
        "Graylog",
        MONITORING,
        "logging",
        default_upstream_port=9000,
        websocket_support=True,
        documentation_url="https://go2docs.graylog.org/",
    ),
    tpl(
        "loki",
        "Loki",
        MONITORING,
        "logging",
        default_upstream_port=3100,
        documentation_url="https://grafana.com/docs/loki/latest/",
    ),
    tpl(
        "jaeger",
        "Jaeger",
        MONITORING,
        "tracing",
        default_upstream_port=16686,
        documentation_url="https://www.jaegertracing.io/docs/",
    ),
    tpl(
        "zipkin",
        "Zipkin",
        MONITORING,
        "tracing",
        default_upstream_port=9411,
        documentation_url="https://zipkin.io/pages/documentation.html",
    ),
    # identity-authentication
    tpl(
        "authentik",
        "Authentik",
        IDENTITY,
        "identity-provider",
        availability_level="pro",
        optimized=True,
        default_upstream_port=9000,
        websocket_support=True,
        documentation_url="https://docs.goauthentik.io/",
    ),
    tpl(
        "keycloak",
        "Keycloak",
        IDENTITY,
        "identity-provider",
        availability_level="pro",
        optimized=True,
        default_upstream_port=8080,
        websocket_support=True,
        documentation_url="https://www.keycloak.org/documentation",
    ),
    tpl(
        "authelia",
        "Authelia",
        IDENTITY,
        "identity-provider",
        default_upstream_port=9091,
        documentation_url="https://www.authelia.com/",
    ),
    tpl(
        "freeipa",
        "FreeIPA",
        IDENTITY,
        "directory",
        default_upstream_protocol="https",
        default_upstream_port=443,
        documentation_url="https://www.freeipa.org/page/Documentation",
    ),
    tpl(
        "ldap-admin",
        "LDAP Admin",
        IDENTITY,
        "directory",
        default_upstream_port=8080,
        documentation_url="https://ldap-account-manager.org/lamcms/",
    ),
    tpl(
        "phpldapadmin",
        "phpLDAPadmin",
        IDENTITY,
        "directory",
        default_upstream_port=8080,
        documentation_url="https://phpldapadmin.sourceforge.net/wiki/index.php/Main_Page",
    ),
    # web-hosting-control-panels
    tpl(
        "hestiacp",
        "HestiaCP",
        HOSTING,
        "control-panel",
        availability_level="pro",
        default_upstream_port=8083,
        documentation_url="https://hestiacp.com/docs/",
    ),
    tpl(
        "cpanel",
        "cPanel",
        HOSTING,
        "control-panel",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=2083,
        documentation_url="https://docs.cpanel.net/",
    ),
    tpl(
        "plesk",
        "Plesk",
        HOSTING,
        "control-panel",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=8443,
        documentation_url="https://docs.plesk.com/",
    ),
    tpl(
        "directadmin",
        "DirectAdmin",
        HOSTING,
        "control-panel",
        availability_level="pro",
        default_upstream_protocol="https",
        default_upstream_port=2222,
        documentation_url="https://docs.directadmin.com/",
    ),
    tpl(
        "ispconfig",
        "ISPConfig",
        HOSTING,
        "control-panel",
        default_upstream_protocol="https",
        default_upstream_port=8080,
        documentation_url="https://www.ispconfig.org/documentation/",
    ),
    tpl(
        "cyberpanel",
        "CyberPanel",
        HOSTING,
        "control-panel",
        default_upstream_protocol="https",
        default_upstream_port=8090,
        documentation_url="https://cyberpanel.net/KnowledgeBase/",
    ),
    # collaboration-communication
    tpl(
        "mattermost",
        "Mattermost",
        COLLAB,
        "chat",
        availability_level="pro",
        default_upstream_port=8065,
        websocket_support=True,
        documentation_url="https://docs.mattermost.com/",
    ),
    tpl(
        "rocketchat",
        "Rocket.Chat",
        COLLAB,
        "chat",
        availability_level="pro",
        default_upstream_port=3000,
        websocket_support=True,
        documentation_url="https://docs.rocket.chat/",
    ),
    tpl(
        "zulip",
        "Zulip",
        COLLAB,
        "chat",
        default_upstream_port=80,
        websocket_support=True,
        documentation_url="https://zulip.com/help/",
    ),
    tpl(
        "jitsi-meet",
        "Jitsi Meet",
        COLLAB,
        "video-conferencing",
        availability_level="pro",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=443,
        websocket_support=True,
        documentation_url="https://jitsi.github.io/handbook/docs/intro/",
    ),
    tpl(
        "bigbluebutton",
        "BigBlueButton",
        COLLAB,
        "video-conferencing",
        default_upstream_protocol="https",
        default_upstream_port=443,
        websocket_support=True,
        documentation_url="https://docs.bigbluebutton.org/",
    ),
    tpl(
        "mailcow",
        "Mailcow",
        COLLAB,
        "mail",
        availability_level="pro",
        optimized=True,
        default_upstream_port=8080,
        websocket_support=True,
        large_upload_support=True,
        recommended_client_max_body_size="50m",
        documentation_url="https://docs.mailcow.email/",
    ),
    tpl(
        "mailu",
        "Mailu",
        COLLAB,
        "mail",
        default_upstream_port=80,
        documentation_url="https://mailu.io/",
    ),
    tpl(
        "roundcube",
        "Roundcube",
        COLLAB,
        "mail",
        default_upstream_port=80,
        documentation_url="https://github.com/roundcube/roundcubemail/wiki",
    ),
    tpl(
        "zimbra",
        "Zimbra",
        COLLAB,
        "mail",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=8443,
        documentation_url="https://www.zimbra.com/documentation/",
    ),
    # source-control-devops
    tpl(
        "gitea",
        "Gitea",
        DEVOPS,
        "git-hosting",
        default_upstream_port=3000,
        documentation_url="https://docs.gitea.com/",
    ),
    tpl(
        "gitlab",
        "GitLab",
        DEVOPS,
        "git-hosting",
        availability_level="pro",
        optimized=True,
        default_upstream_protocol="https",
        default_upstream_port=443,
        websocket_support=True,
        large_upload_support=True,
        documentation_url="https://docs.gitlab.com/",
    ),
    tpl(
        "forgejo",
        "Forgejo",
        DEVOPS,
        "git-hosting",
        default_upstream_port=3000,
        documentation_url="https://forgejo.org/docs/latest/",
    ),
    tpl(
        "jenkins",
        "Jenkins",
        DEVOPS,
        "ci-cd",
        availability_level="pro",
        default_upstream_port=8080,
        websocket_support=True,
        documentation_url="https://www.jenkins.io/doc/",
    ),
    tpl(
        "drone-ci",
        "Drone CI",
        DEVOPS,
        "ci-cd",
        default_upstream_port=80,
        documentation_url="https://docs.drone.io/",
    ),
    tpl(
        "teamcity",
        "TeamCity",
        DEVOPS,
        "ci-cd",
        availability_level="enterprise",
        default_upstream_port=8111,
        websocket_support=True,
        documentation_url="https://www.jetbrains.com/help/teamcity/",
    ),
    tpl(
        "nexus-repository",
        "Nexus Repository",
        DEVOPS,
        "artifact-repository",
        availability_level="enterprise",
        default_upstream_port=8081,
        large_upload_support=True,
        documentation_url="https://help.sonatype.com/en/sonatype-nexus-repository.html",
    ),
    tpl(
        "jfrog-artifactory",
        "JFrog Artifactory",
        DEVOPS,
        "artifact-repository",
        availability_level="enterprise",
        default_upstream_port=8082,
        large_upload_support=True,
        documentation_url="https://jfrog.com/help/r/jfrog-artifactory-documentation",
    ),
    # storage-backup
    tpl(
        "minio",
        "MinIO",
        STORAGE,
        "object-storage",
        availability_level="pro",
        optimized=True,
        default_upstream_port=9000,
        websocket_support=True,
        large_upload_support=True,
        documentation_url="https://min.io/docs/minio/linux/index.html",
    ),
    tpl(
        "ceph-dashboard",
        "Ceph Dashboard",
        STORAGE,
        "storage-management",
        default_upstream_protocol="https",
        default_upstream_port=8443,
        documentation_url="https://docs.ceph.com/en/latest/mgr/dashboard/",
    ),
    tpl(
        "truenas",
        "TrueNAS",
        STORAGE,
        "nas",
        availability_level="pro",
        default_upstream_protocol="https",
        default_upstream_port=443,
        documentation_url="https://www.truenas.com/docs/",
    ),
    tpl(
        "openmediavault",
        "OpenMediaVault",
        STORAGE,
        "nas",
        default_upstream_port=80,
        documentation_url="https://docs.openmediavault.org/",
    ),
    tpl(
        "urbackup",
        "UrBackup",
        STORAGE,
        "backup",
        default_upstream_port=55414,
        large_upload_support=True,
        documentation_url="https://www.urbackup.org/administration_manual.html",
    ),
    tpl(
        "restic-web",
        "Restic Web",
        STORAGE,
        "backup",
        default_upstream_port=8000,
        documentation_url="https://github.com/Franziska-Peter/restic-web",
    ),
    tpl(
        "proxmox-backup-server",
        "Proxmox Backup Server",
        STORAGE,
        "backup",
        availability_level="pro",
        default_upstream_protocol="https",
        default_upstream_port=8007,
        large_upload_support=True,
        documentation_url="https://pbs.proxmox.com/docs/",
    ),
    # self-hosted-productivity
    tpl(
        "paperless-ngx",
        "Paperless-ngx",
        PRODUCTIVITY,
        "document-management",
        default_upstream_port=8000,
        large_upload_support=True,
        documentation_url="https://docs.paperless-ngx.com/",
    ),
    tpl(
        "mayan-edms",
        "Mayan EDMS",
        PRODUCTIVITY,
        "document-management",
        default_upstream_port=80,
        large_upload_support=True,
        documentation_url="https://docs.mayan-edms.com/",
    ),
    tpl(
        "bookstack",
        "BookStack",
        PRODUCTIVITY,
        "wiki",
        default_upstream_port=80,
        documentation_url="https://www.bookstackapp.com/docs/",
    ),
    tpl(
        "wiki-js",
        "Wiki.js",
        PRODUCTIVITY,
        "wiki",
        default_upstream_port=3000,
        documentation_url="https://docs.requarks.io/",
    ),
    tpl(
        "mediawiki",
        "MediaWiki",
        PRODUCTIVITY,
        "wiki",
        default_upstream_port=80,
        large_upload_support=True,
        documentation_url="https://www.mediawiki.org/wiki/Documentation",
    ),
    tpl(
        "outline",
        "Outline",
        PRODUCTIVITY,
        "wiki",
        default_upstream_port=3000,
        websocket_support=True,
        documentation_url="https://docs.getoutline.com/",
    ),
    tpl(
        "nextcloud",
        "Nextcloud",
        PRODUCTIVITY,
        "file-sync",
        optimized=True,
        default_upstream_port=8080,
        websocket_support=True,
        large_upload_support=True,
        recommended_client_max_body_size="10G",
        documentation_url="https://docs.nextcloud.com/",
    ),
    tpl(
        "owncloud",
        "ownCloud",
        PRODUCTIVITY,
        "file-sync",
        default_upstream_port=8080,
        websocket_support=True,
        large_upload_support=True,
        documentation_url="https://doc.owncloud.com/",
    ),
    tpl(
        "seafile",
        "Seafile",
        PRODUCTIVITY,
        "file-sync",
        default_upstream_port=8000,
        large_upload_support=True,
        documentation_url="https://manual.seafile.com/",
    ),
    tpl(
        "immich",
        "Immich",
        PRODUCTIVITY,
        "photos",
        default_upstream_port=2283,
        large_upload_support=True,
        documentation_url="https://immich.app/docs",
    ),
    tpl(
        "wordpress",
        "WordPress",
        PRODUCTIVITY,
        "cms",
        default_upstream_port=8080,
        large_upload_support=True,
        recommended_client_max_body_size="64m",
        documentation_url="https://wordpress.org/documentation/",
    ),
    # media-entertainment
    tpl(
        "jellyfin",
        "Jellyfin",
        MEDIA,
        "media-server",
        default_upstream_port=8096,
        websocket_support=True,
        large_upload_support=True,
        recommended_client_max_body_size="0",
        documentation_url="https://jellyfin.org/docs/",
    ),
    tpl(
        "plex",
        "Plex",
        MEDIA,
        "media-server",
        default_upstream_port=32400,
        documentation_url="https://support.plex.tv/",
    ),
    tpl(
        "emby",
        "Emby",
        MEDIA,
        "media-server",
        default_upstream_port=8096,
        websocket_support=True,
        documentation_url="https://emby.media/support.html",
    ),
    tpl(
        "sonarr",
        "Sonarr",
        MEDIA,
        "media-automation",
        default_upstream_port=8989,
        documentation_url="https://wiki.servarr.com/sonarr",
    ),
    tpl(
        "radarr",
        "Radarr",
        MEDIA,
        "media-automation",
        default_upstream_port=7878,
        documentation_url="https://wiki.servarr.com/radarr",
    ),
    tpl(
        "lidarr",
        "Lidarr",
        MEDIA,
        "media-automation",
        default_upstream_port=8686,
        documentation_url="https://wiki.servarr.com/lidarr",
    ),
    tpl(
        "readarr",
        "Readarr",
        MEDIA,
        "media-automation",
        default_upstream_port=8787,
        documentation_url="https://wiki.servarr.com/readarr",
    ),
    tpl(
        "bazarr",
        "Bazarr",
        MEDIA,
        "media-automation",
        default_upstream_port=6767,
        documentation_url="https://wiki.bazarr.media/",
    ),
    tpl(
        "prowlarr",
        "Prowlarr",
        MEDIA,
        "media-automation",
        default_upstream_port=9696,
        documentation_url="https://wiki.servarr.com/prowlarr",
    ),
    tpl(
        "navidrome",
        "Navidrome",
        MEDIA,
        "music",
        default_upstream_port=4533,
        documentation_url="https://www.navidrome.org/docs/",
    ),
    tpl(
        "audiobookshelf",
        "Audiobookshelf",
        MEDIA,
        "audiobooks",
        default_upstream_port=80,
        documentation_url="https://www.audiobookshelf.org/docs",
    ),
    # smart-home-iot
    tpl(
        "home-assistant",
        "Home Assistant",
        SMART_HOME,
        "home-automation",
        optimized=True,
        default_upstream_port=8123,
        websocket_support=True,
        documentation_url="https://www.home-assistant.io/docs/",
    ),
    tpl(
        "openhab",
        "openHAB",
        SMART_HOME,
        "home-automation",
        default_upstream_port=8080,
        websocket_support=True,
        documentation_url="https://www.openhab.org/docs/",
    ),
    tpl(
        "node-red",
        "Node-RED",
        SMART_HOME,
        "automation",
        default_upstream_port=1880,
        websocket_support=True,
        documentation_url="https://nodered.org/docs/",
    ),
    tpl(
        "zigbee2mqtt",
        "Zigbee2MQTT",
        SMART_HOME,
        "iot-bridge",
        default_upstream_port=8080,
        websocket_support=True,
        documentation_url="https://www.zigbee2mqtt.io/",
    ),
    tpl(
        "mosquitto",
        "Mosquitto MQTT",
        SMART_HOME,
        "mqtt",
        default_upstream_port=9001,
        websocket_support=True,
        documentation_url="https://mosquitto.org/documentation/",
        notes="Port 9001 is the default WebSocket listener; MQTT TCP uses 1883.",
    ),
    # ai-llm-platforms
    tpl(
        "open-webui",
        "Open WebUI",
        AI,
        "chat-ui",
        optimized=True,
        default_upstream_port=8080,
        websocket_support=True,
        documentation_url="https://docs.openwebui.com/",
    ),
    tpl(
        "librechat",
        "LibreChat",
        AI,
        "chat-ui",
        default_upstream_port=3080,
        websocket_support=True,
        documentation_url="https://www.librechat.ai/docs",
    ),
    tpl(
        "anythingllm",
        "AnythingLLM",
        AI,
        "chat-ui",
        default_upstream_port=3001,
        websocket_support=True,
        documentation_url="https://docs.anythingllm.com/",
    ),
    tpl(
        "ollama",
        "Ollama",
        AI,
        "inference",
        default_upstream_port=11434,
        large_upload_support=True,
        documentation_url="https://github.com/ollama/ollama/blob/main/docs/api.md",
    ),
    tpl(
        "vllm",
        "vLLM",
        AI,
        "inference",
        default_upstream_port=8000,
        documentation_url="https://docs.vllm.ai/",
    ),
    tpl(
        "text-generation-webui",
        "Text Generation WebUI",
        AI,
        "inference",
        default_upstream_port=7860,
        websocket_support=True,
        documentation_url="https://github.com/oobabooga/text-generation-webui/wiki",
    ),
    tpl(
        "searxng",
        "SearXNG",
        AI,
        "search",
        default_upstream_port=8080,
        documentation_url="https://docs.searxng.org/",
    ),
    # security
    tpl(
        "vaultwarden",
        "Vaultwarden",
        SECURITY,
        "password-manager",
        default_upstream_port=80,
        documentation_url="https://github.com/dani-garcia/vaultwarden/wiki",
    ),
    tpl(
        "bitwarden",
        "Bitwarden Self-Hosted",
        SECURITY,
        "password-manager",
        default_upstream_port=80,
        documentation_url="https://bitwarden.com/help/install-on-premise/",
    ),
    tpl(
        "wazuh",
        "Wazuh",
        SECURITY,
        "siem",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=443,
        documentation_url="https://documentation.wazuh.com/",
    ),
    tpl(
        "security-onion",
        "Security Onion",
        SECURITY,
        "siem",
        availability_level="enterprise",
        default_upstream_protocol="https",
        default_upstream_port=443,
        documentation_url="https://docs.securityonion.net/",
    ),
    tpl(
        "openvas",
        "OpenVAS",
        SECURITY,
        "vulnerability-scanner",
        default_upstream_protocol="https",
        default_upstream_port=9392,
        documentation_url="https://www.openvas.org/",
    ),
    tpl(
        "greenbone",
        "Greenbone",
        SECURITY,
        "vulnerability-scanner",
        default_upstream_protocol="https",
        default_upstream_port=9392,
        documentation_url="https://greenbone.net/en/documentation/",
    ),
    # business-applications
    tpl(
        "suitecrm",
        "SuiteCRM",
        BUSINESS,
        "crm",
        default_upstream_port=80,
        documentation_url="https://docs.suitecrm.com/",
    ),
    tpl(
        "espocrm",
        "EspoCRM",
        BUSINESS,
        "crm",
        default_upstream_port=80,
        documentation_url="https://docs.espocrm.com/",
    ),
    tpl(
        "erpnext",
        "ERPNext",
        BUSINESS,
        "erp",
        availability_level="pro",
        default_upstream_port=8080,
        documentation_url="https://docs.frappe.io/erpnext/",
    ),
    tpl(
        "odoo",
        "Odoo",
        BUSINESS,
        "erp",
        availability_level="pro",
        default_upstream_port=8069,
        websocket_support=True,
        documentation_url="https://www.odoo.com/documentation/",
    ),
    tpl(
        "zammad",
        "Zammad",
        BUSINESS,
        "helpdesk",
        default_upstream_port=3000,
        websocket_support=True,
        documentation_url="https://docs.zammad.org/",
    ),
    tpl(
        "glpi",
        "GLPI",
        BUSINESS,
        "itsm",
        default_upstream_port=80,
        documentation_url="https://glpi-project.org/documentation/",
    ),
    tpl(
        "osticket",
        "osTicket",
        BUSINESS,
        "helpdesk",
        default_upstream_port=80,
        documentation_url="https://docs.osticket.com/",
    ),
    # databases
    tpl(
        "phpmyadmin",
        "phpMyAdmin",
        DATABASES,
        "database-admin",
        default_upstream_port=80,
        documentation_url="https://docs.phpmyadmin.net/",
        security_notes="Restrict database admin UIs to trusted networks and strong authentication.",
    ),
    tpl(
        "adminer",
        "Adminer",
        DATABASES,
        "database-admin",
        default_upstream_port=8080,
        documentation_url="https://www.adminer.org/",
        security_notes="Restrict database admin UIs to trusted networks and strong authentication.",
    ),
    tpl(
        "pgadmin",
        "pgAdmin",
        DATABASES,
        "database-admin",
        default_upstream_port=5050,
        documentation_url="https://www.pgadmin.org/docs/",
        security_notes="Restrict database admin UIs to trusted networks and strong authentication.",
    ),
    tpl(
        "mongo-express",
        "Mongo Express",
        DATABASES,
        "database-admin",
        default_upstream_port=8081,
        documentation_url="https://github.com/mongo-express/mongo-express",
        security_notes="Restrict database admin UIs to trusted networks and strong authentication.",
    ),
    tpl(
        "redis-commander",
        "Redis Commander",
        DATABASES,
        "database-admin",
        default_upstream_port=8081,
        documentation_url="https://github.com/joeferner/redis-commander",
        security_notes="Restrict database admin UIs to trusted networks and strong authentication.",
    ),
    # networking
    tpl(
        "unifi-controller",
        "UniFi Controller",
        NETWORKING,
        "network-controller",
        default_upstream_protocol="https",
        default_upstream_port=8443,
        websocket_support=True,
        documentation_url="https://help.ui.com/",
    ),
    tpl(
        "omada-controller",
        "Omada Controller",
        NETWORKING,
        "network-controller",
        default_upstream_protocol="https",
        default_upstream_port=8043,
        websocket_support=True,
        documentation_url="https://support.omadanetworks.com/",
    ),
    tpl(
        "pi-hole",
        "Pi-hole",
        NETWORKING,
        "dns",
        default_upstream_port=80,
        documentation_url="https://docs.pi-hole.net/",
    ),
    tpl(
        "adguard-home",
        "AdGuard Home",
        NETWORKING,
        "dns",
        default_upstream_port=3000,
        documentation_url="https://github.com/AdguardTeam/AdGuardHome/wiki",
    ),
    tpl(
        "technitium-dns",
        "Technitium DNS",
        NETWORKING,
        "dns",
        default_upstream_port=5380,
        documentation_url="https://technitium.com/dns/",
    ),
    tpl(
        "wireguard-ui",
        "WireGuard UI",
        NETWORKING,
        "vpn",
        default_upstream_port=5000,
        documentation_url="https://github.com/ngoduykhanh/wireguard-ui",
    ),
    tpl(
        "headscale",
        "Headscale",
        NETWORKING,
        "vpn",
        default_upstream_port=8080,
        documentation_url="https://headscale.net/stable/",
    ),
    tpl(
        "openvpn-access-server",
        "OpenVPN Access Server",
        NETWORKING,
        "vpn",
        default_upstream_protocol="https",
        default_upstream_port=943,
        documentation_url="https://openvpn.net/access-server-manual/",
    ),
    # developer-tools
    tpl(
        "hoppscotch",
        "Hoppscotch",
        DEVELOPER,
        "api-client",
        default_upstream_port=3000,
        documentation_url="https://docs.hoppscotch.io/",
    ),
    tpl(
        "postgrest",
        "PostgREST",
        DEVELOPER,
        "api",
        default_upstream_port=3000,
        documentation_url="https://postgrest.org/en/stable/",
    ),
    tpl(
        "swagger-ui",
        "Swagger UI",
        DEVELOPER,
        "api-docs",
        default_upstream_port=8080,
        documentation_url="https://swagger.io/tools/swagger-ui/",
    ),
    tpl(
        "redoc",
        "Redoc",
        DEVELOPER,
        "api-docs",
        default_upstream_port=8080,
        documentation_url="https://redocly.com/docs/redoc/",
    ),
    tpl(
        "backstage",
        "Backstage",
        DEVELOPER,
        "developer-portal",
        availability_level="enterprise",
        default_upstream_port=7007,
        documentation_url="https://backstage.io/docs/",
    ),
    # general
    tpl(
        "custom",
        "Custom",
        GENERAL,
        "general",
        description="Blank starting point with a single HTTP route.",
        default_upstream_port=8080,
        http_to_https_redirect_default=False,
        documentation_url=None,
    ),
    tpl(
        "wordpress",
        "WordPress",
        GENERAL,
        "cms",
        description="Typical WordPress site with HTTPS redirect and large upload support.",
        default_upstream_port=8080,
        large_upload_support=True,
        recommended_client_max_body_size="64m",
        documentation_url="https://wordpress.org/documentation/",
    ),
]


def group_templates(templates: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for template in templates:
        grouped[template["group"]].append(template)
    return grouped


def write_group_files(grouped: dict[str, list[dict[str, Any]]]) -> tuple[int, int]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    file_count = 0
    template_count = 0

    for group_slug in sorted(grouped):
        templates = grouped[group_slug]
        output_path = OUTPUT_DIR / f"{group_slug}.yaml"
        payload = {"templates": templates}
        with output_path.open("w", encoding="utf-8") as handle:
            yaml.safe_dump(
                payload,
                handle,
                sort_keys=False,
                default_flow_style=False,
                allow_unicode=True,
                width=120,
            )
        file_count += 1
        template_count += len(templates)

    return file_count, template_count


def main() -> None:
    grouped = group_templates(TEMPLATES)
    file_count, template_count = write_group_files(grouped)
    print(f"Generated {file_count} catalog files with {template_count} templates.")
    print(f"Output directory: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
